Repository peopledoc/broccoli-styledown, pull requests merged in 2021-11, with the labels that each got.

#54 Refine information in `package.json`+ update year & company in `LICENSE`
  LICENSE
  package.json
Labels: documentation

#55 CI - New workflow to auto-update list of contributors
  .github/workflows/contributors.yml
  README.md
Labels: ci

#56 doc: update README documentation
  .github/workflows/main.yml
  README.md
  package.json
Labels: documentation, ci

#58 doc: fix README
  README.md
Labels: documentation
